var en=[[" alpha "," \\alpha "],[" beta "," \\beta "],[" gamma "," \\gamma "],[" delta "," \\delta "],[" epsilon "," \\epsilon "],[" zeta "," \\zeta "],
[" eta "," \\eta "],[" theta "," \\theta "],[" iota "," \\iota "],[" kappa "," \\kappa "],[" lambda "," \\lambda "],[" mu "," \\mu "],[" nu "," \\nu "],[" xi "," \\xi "],
[" phi "," \\phi "],[" omikron "," \\omikron "],[" pi "," \\pi "],[" rho "," \\rho "],[" sigma "," \\sigma "],[" tau "," \\tau "],[" upsilon "," \\upsilon "],[" phi "," \\phi "],
[" chi "," \\chi "],[" psi "," \\psi "],[" omega "," \\omega "],[","," , "],["."," . "],["?"," ? "],["!"," ! "],[" zero "," 0 "],[" one "," 1 "],[" two "," 2 "],
[" three "," 3 "],[" four "," 4 "],[" five "," 5 "],[" six "," 6 "],[" seven "," 7 "],[" eight "," 8 "],[" nine "," 9 "],[" ten "," 10 "],[" alice "," a "],
[" bravo "," b "],[" charlie "," c "],[" dingo "," d "],[" echo "," e "],[" foxtrot "," f "],[" golf "," g "],[" hotel "," h "],[" india "," i"],[" juliet "," j "],
[" kilo "," k "],[" lima "," l "],[" mike "," m "],[" november "," n "],[" oscar "," o "],[" papa "," p "],[" quebec "," q "],[" romeo "," r "],[" sierra "," s "],
[" tango "," t "],[" uniform "," u "],[" victor "," v "],[" whiskey "," w "],[" x-ray "," x "],[" xray "," x "],[" yankee "," y "],[" zulu "," z "],[" america "," A "],
[" boston "," B "],[" canada "," C "],[" denmark "," D "],[" england "," E "],[" florida "," F "],[" germany "," G "],[" honolulu "," H "],[" italy "," I "],[" japan "," J "],
[" kenya "," K "],[" london "," L "],[" mexico "," M "],[" norway "," N "],[" ontario "," O "],[" peru "," P "],[" qatar "," Q "],[" rome "," R "],[" sydney "," S "],
[" tokyo "," T "],[" united "," U "],[" virginia"," V "],[" washington "," W "],[" xylophone "," X "],[" yokohama "," Y "],[" zanzibar "," Z "],[" open curly bracket "," { "],
[" close curly bracket "," } "],[" new line "," \\\\ "],[" close apex "," } "],[" open apex "," ^{ "],[" close subscript "," } "],[" open subscript "," _{ "],
[" open parenthesis "," \\left( "],[" close parenthesis "," \\right) "],[" begin equation "," \\begin{equation} "],[" end equation "," \\end{equation} "],[" and "," & "],
[" dollar "," $ "],[" math box "," \\mbox{ "],[" open "," { "],[" close "," } "],[" begin align "," \\begin{align} "],[" end align "," \\end{align} "],
[" which implies that "," \\Rightarrow "],[" which implies "," \\Rightarrow "],[" implies that "," \\Rightarrow "],[" implies "," \\Rightarrow "],
[" if and only if "," \\Leftrightarrow "],[" only if "," \\Leftarrow "],[" if "," \\Leftarrow "],[" such that "," | "],[" therefore "," \\therefore "],[" for all "," \\forall "],
[" there exists "," \\exists "],[" exists "," \\exists "],[" set minus "," \\setminus "],[" big intersect "," \\bigcap "],[" intersect "," \\cap "],[" big union "," \\bigcup "],
[" union "," \\cup "],[" in "," \\in "],[" is an element of "," \\in "],[" is a subset of "," \\subseteq "],[" the set of natural numbers "," \\mathbb{N} "],
[" the set of integer numbers "," \\mathbb{Z} "],[" the set of rational numbers "," \\mathbb{Q} "],[" the set of real numbers "," \\mathbb{R} "],
[" the set of complex numbers "," \\mathbb{C} "],[" set of natural numbers "," \\mathbb{N} "],[" set of integer numbers "," \\mathbb{Z} "],
[" set of rational numbers "," \\mathbb{Q} "],[" set of real numbers "," \\mathbb{R} "],[" set of complex numbers "," \\mathbb{C} "],
[" set of all natural numbers "," \\mathbb{N} "],[" set of all integer numbers "," \\mathbb{Z} "],[" set of all rational numbers "," \\mathbb{Q} "],
[" set of all real numbers "," \\mathbb{R} "],[" set of all complex numbers "," \\mathbb{C} "],[" to the power of "," ^{ "],[" fraction "," \\frac{ "],
[" over "," }{ "],[" integral "," \\int "],[" from "," _{ "],[" to "," }^{ "],[" infinity "," \\infty "],[" of "," } "],[" sum "," \\sum "],[" equal "," = "],[" equals "," = "],
[" not equal to "," \\neq "],[" plus or minus "," \\pm "],[" square root of "," \\sqrt{ "],[" square root "," \\sqrt{ "],[" plus "," + "],[" minus "," - "],[" divided by "," / "],
[" times "," \\times "],[" greater than or equal to "," \\geq "],[" less than or equal to "," \\leq "],[" less than "," < "],[" greater than "," > "],[" limit as "," \\lim_{ "],
[" limit "," \\lim "],[" goes to "," \\rightarrow "],[" from above "," ^+} "],[" from below "," ^-} "],[" scalar "," \\cdot "],[" vector "," \\vec{ "],[" vectorial "," \\times "],
[" partial "," \\partial "],[" product "," \\product "],[" dx by dy "," \\frac{dx}{dy} "],[" dx by "," \\frac{dx}{ "],[" or "," \\vee "],[" squared "," ^2 "],[" cubed "," ^3 "],
[" factorial "," ! "],[" sine "," \\sin "],[" sin "," \\sin "],[" cosine "," \\cos "],[" cos "," \\cos "],[" tangent "," \\tan "],[" tan "," \\tan "],[" exponential "," \\exp{ "],
[" exp "," \\exp{ "],[" log "," \\log "],[" logarithm "," \\log "],[" left right arrow ","\\leftrightarrow "],[" left arrow "," \\leftarrow "],[" right arrow "," \\rightarrow "]];




