var it=[[" alfa "," \\alpha "],[" beta "," \\beta "],[" gamma "," \\gamma "],[" delta "," \\delta "],[" epsilon "," \\epsilon "],
        [" zeta "," \\zeta "],[" eta "," \\eta "],[" theta "," \\theta "],[" iota "," \\iota "],[" kappa "," \\kappa "],
        [" lambda "," \\lambda "],[" mu "," \\mu "],[" nu "," \\nu "],[" xi "," \\xi "],[" fi "," \\phi "],[" omikron "," \\omikron "],
        [" pi "," \\pi "],[" ro "," \\rho "],[" sigma "," \\sigma "],[" tau "," \\tau "],[" upsilon "," \\upsilon "],[" phi "," \\phi "],
        [" chi "," \\chi "],[" psi "," \\psi "],[" omega "," \\omega "],[","," , "],["."," . "],["?"," ? "],["!"," ! "],[" zero "," 0 "],
        [" uno "," 1 "],[" due "," 2 "],[" tre "," 3 "],[" quattro "," 4 "],[" cinque "," 5 "],[" sei "," 6 "],[" sette "," 7 "],
        [" otto "," 8 "],[" nove "," 9 "],[" dieci "," 10 "],[" alice "," a "],[" bi "," b "],[" ci "," c "],[" di "," d "],
        [" echo "," e "],[" effe "," f "],[" golf "," g "],[" gi "," g "],[" hotel "," h "],[" india "," i"],[" juliet "," j "],
        [" kappa "," k "],[" elle "," l "],[" emme "," m "],[" enne "," n "],[" oscar "," o "],[" pi "," p "],[" qu "," q "],
        [" erre "," r "],[" esse "," s "],[" ti "," t "],[" uniform "," u "],[" vi "," v "],[" doppia vu "," w "],[" x-ray "," x "],
        [" xray "," x "],[" ipsilon "," y "],[" zeta "," z "],[" ancona "," A "],[" bologna "," B "],[" como "," C "],
        [" domodossola "," D "],[" empoli "," E "],[" firenze "," F "],[" genova "," G "],[" hannover "," H "],[" imola "," I "],
        [" jesolo "," J "],[" k "," K "],[" livorno "," L "],[" milano "," M "],[" napoli "," N "],[" otranto "," O "],[" perugia "," P "],
        [" qebec "," Q "],[" roma "," R "],[" siena "," S "],[" taranto "," T "],[" udine "," U "],[" venezia"," V "],[" w "," W "],
        [" xilofono "," X "],[" yoghurt "," Y "],[" zanzibar "," Z "],[" apri graffa "," { "],[" chiudi graffa "," } "],
        [" apri parentesi graffa "," { "],[" chiudi parentesi graffa "," } "],[" nuova line "," \\\\ "],[" chiudi apice "," } "],
        [" apri apice "," ^{ "],[" close subscript "," } "],[" open subscript "," _{ "],[" apri parentesi "," \\left( "],
        [" chiudi parentesi "," \\right) "],[" apri parentesi tonda "," \\left( "],[" chiudi parentesi tonda "," \\right) "],
        [" apri tonda "," \\left( "],[" chiudi tonda "," \\right) "],[" nuova equazione "," \\begin{equation} "],
        [" apri equazione "," \\begin{equation} "],[" chiudi equazione "," \\end{equation} "],[" fine equazione "," \\end{equation} "],
        [" e commerciale "," & "],[" dollaro "," $ "],[" scatola matematica "," \\mbox{ "],[" apri "," { "],[" chiudi "," } "],
        [" inizia allineato "," \\begin{align} "],[" fine allineato "," \\end{align} "],[" apri allineato "," \\begin{align} "],
        [" chiudi allineato "," \\end{align} "],[" che implica che "," \\Rightarrow "],[" che implica "," \\Rightarrow "],
        [" implica che "," \\Rightarrow "],[" implica "," \\Rightarrow "],[" se e solo se "," \\Leftrightarrow "],
        [" solo se "," \\Leftarrow "],[" se "," \\Leftarrow "],[" tale che "," | "],[" dunque "," \\therefore "],
        [" per ogni "," \\forall "],[" esiste "," \\exists "],[" meno insiemi "," \\setminus "],[" intersezione grande "," \\bigcap "],
        [" intersecato grande "," \\bigcap "],[" intersezione "," \\cap "],[" intersecato "," \\cap "],[" grande unione "," \\bigcup "],
        [" grande unito "," \\bigcup "],[" unione "," \\cup "],[" unito "," \\cup "],[" appartiene "," \\in "],[" appartiene a "," \\in "],
        [" è un elemento di "," \\in "],[" è un sottoinsieme di "," \\subseteq "],[" l'insieme dei numeri naturali "," \\mathbb{N} "],
        [" l'insieme dei numeri interi "," \\mathbb{Z} "],[" l'insieme dei numeri razionali "," \\mathbb{Q} "],
        [" l'insieme dei numeri reali "," \\mathbb{R} "],[" l'insieme dei numeri complessi "," \\mathbb{C} "],
        [" insieme dei numeri naturali "," \\mathbb{N} "],[" insieme dei numeri interi "," \\mathbb{Z} "],
        [" insieme dei numeri razionali "," \\mathbb{Q} "],[" insieme dei numeri reali "," \\mathbb{R} "],
        [" insieme dei numeri complessi "," \\mathbb{C}  "],[" elevato a "," ^{ "],[" frazione "," \\frac{ "],[" su "," }{ "],
        [" integrale "," \\int "],[" da "," _{ "],[" infinito "," \\infty "],[" somma "," \\sum "],[" sommatoria "," \\sum "],
        [" uguale "," = "],[" diverso "," \\neq "],[" non uguale "," \\neq "],[" più o meno "," \\pm "],[" radice di "," \\sqrt{ "],
        [" radice quadrata di "," \\sqrt{ "],[" radice quadrata "," \\sqrt{"],[" radice "," \\sqrt{ "],[" più "," + "],[" meno "," - "],
        [" diviso "," / "],[" moltiplicato per "," \\times "],[" maggiore uguale a "," \\geq "],[" minore uguale a "," \\leq "],
        [" maggiore uguale di "," \\geq "],[" minore uguale di "," \\leq  "],[" maggiore uguale "," \\geq "],[" minore uguale "," \\leq "],
        [" minore di "," < "],[" maggiore di "," > "],[" minore "," < "],[" maggiore "," > "],[" limite per "," \\lim_{ "],
        [" limite "," \\lim "],[" che va a "," \\rightarrow "],[" da sopra "," ^+} "],[" da sotto "," ^-} "],[" scalare "," \\cdot "],
        [" vettore "," \\vec{ "],[" vectoriale "," \\times "],[" parziale "," \\partial "],[" prodotto "," \\product "],
        [" produttoria "," \\product "],[" dx su dy "," \\frac{dx}{dy} "],[" dx su "," \\frac{dx}{ "],[" al quadrato "," ^2 "],
        [" alla seconda "," ^2 "],[" alla terza "," ^3 "],
        [" al cubo "," ^3 "],[" fattoriale "," ! "],[" di "," } "],[" per "," \\times "],[" seno "," \\sin "],[" sen "," \\sin "],
        [" coseno "," \\cos "],[" cos "," \\cos "],[" tangente "," \\tan "],[" tan "," \\tan "],[" esponenziale "," \\exp{ "],
        [" exp "," \\exp{ "],[" log "," \\log "],[" logaritmo "," \\log "],[" logaritmo di "," \\log "],
        [" freccia sinistra destra ","\\leftrightarrow "],[" freccia sinistra "," \\leftarrow "],[" freccia destra "," \\rightarrow"]]; 
